name: 02 - Security

on:
  workflow_call:

jobs:
  dependency-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Dependency Review
        uses: actions/dependency-review-action@v4

  sast-bandit:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit
        run: bandit -r . -x ./venv,./.venv,./tests -s B101 -f txt

  dependency-vuln-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit

      - name: Audit dependencies
        run: pip-audit -r requirements.txt

  iac-and-secret-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.5
        with:
          cache: true
          version: v0.69.3

      - name: Trivy filesystem scan
        run: |
          trivy fs \
            --scanners misconfig,secret \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            .